apiVersion: ignite.weave.works/v1alpha4
kind: VM
metadata:
  name: jadwalinOnline
  uid: d91559c1-6947-4809-bd11-f56ffe7f3189
spec:
  image:
    oci: weaveworks/ignite-amazonlinux
  cpus: 2
  diskSize: 3GB
  memory: 400MB
  ssh: true
status:
  running: true
