apiVersion: ignite.weave.works/v1alpha4
kind: VM
metadata:
  created: "2022-09-14T06:42:26Z"
  name: jadwalin-online
  uid: d91559c1-6947-4809-bd11-f56ffe7f3189
spec:
  cpus: 2
  diskSize: 3GB
  image:
    oci: weaveworks/ignite-amazonlinux:latest
  kernel:
    cmdLine: console=ttyS0 reboot=k panic=1 pci=off ip=dhcp
    oci: weaveworks/ignite-kernel:5.10.51
  memory: 400MB
  network:
    ports:
    - bindAddress: 10.61.0.17
      hostPort: 8978
      vmPort: 3000
  sandbox:
    oci: weaveworks/ignite:v0.10.0
  ssh: true
  storage: {}
status:
  idPrefix: ""
  image:
    id: oci://docker.io/weaveworks/ignite-amazonlinux@sha256:6b4f3a907b2f848c55a91240a4c0620e5620ac91358088f7c8bcc58139795e9f
    size: 277368KB
  kernel:
    id: oci://docker.io/weaveworks/ignite-kernel@sha256:a992aa9f7b6f5e7945e72610017c3f4f38338ff1452964e30410bb6110a794a7
    size: 73052KB
  network:
    ipAddresses: null
    plugin: ""
  running: true
  runtime:
    id: ""
    name: ""
