apiVersion: ignite.weave.works/v1alpha4
kind: VM
metadata:
  uid: 4f491a9605852407
  created: "2022-09-14T06:42:26Z"
  name: jadwalin-online
spec:
  cpus: 1
  diskSize: 3GB
  image:
    oci: weaveworks/ignite-amazonlinux:latest
  kernel:
    cmdLine: console=ttyS0 reboot=k panic=1 pci=off ip=dhcp
    oci: weaveworks/ignite-amazon-kernel
  memory: 400MB
  network:
    ports:
    - hostPort: 8978
      vmPort: 3000
  sandbox:
    oci: weaveworks/ignite:v0.10.0
  ssh: true 
  storage: {}
status:
  idPrefix: "dev"
  image:
    id: d0c2c32696e1cffc
    size: 270.9MB
  kernel:
    id: 290ff541080c86fb
    size: 71.3MB
  network:
    ipAddresses: [
      10.61.0.17
    ]
    plugin: "cni"
  running: true
  runtime:
    id: ignite-4f491a9605852407
    name: "containerd"
